Head draw func (c использованием функции)
typedd/snake-elm-ui pull request #27
Opened 2022-10-18 23:46 UTC by AVZapevalov

2022-10-19 16:48 UTC, piton182 requested changes

2022-10-19 16:48 UTC, piton182 commented on README.md
> +* Be happy and smile
Это, хоть и верно, к задаче не относится. Если хочешь внести предложение по редакции README, пожалуйста, в отдельном PR. Одна задача = один PR

2022-10-19 16:48 UTC, piton182 commented on src/Main.elm
> +            [ centerX, centerY ]
Здесь под шумок пытаемся пролоббировать изменения, не относящиеся к задаче. Все рац предожения приветствуются, но в отдельных PR, пожалуйста

2022-10-19 16:48 UTC, piton182 commented on src/Main.elm
> +                List.indexedMap (\i row -> asdf i model.x) (List.repeat model.y cell)
Хорошая работа тут!

2022-10-19 16:48 UTC, piton182 commented on src/Main.elm
> +asdf : Int -> Int -> Element msg
Мне все равно, я могу и с такими именами принять, ибо тип говорит гораздо больше, чем само имя, но ты вроде хотел переименовывать?

Хвалю за приоритет работоспособности против "хороших" имен!

2022-10-19 18:21 UTC, AVZapevalov commented on src/Main.elm
> +asdf : Int -> Int -> Element msg
https://github.com/typedd/snake-elm-ui/pull/28

исправленная версия тут

2022-10-26 15:27 UTC, piton182 requested changes

2022-10-26 15:27 UTC, piton182 commented on src/Main.elm
> +    Tick newTime ->
тут отступа не хватает

чистота в отступах - важная вещь!

2022-10-26 15:27 UTC, piton182 commented on src/Main.elm
> +        ( { model | snakeHeadX = model.snakeHeadX + 1 }
Интересно, а что происходит, когда координата выходит за пределы поля?

2022-10-26 15:27 UTC, piton182 commented on README.md
> +* Be happy and smile
Этот коммент 7 дней без внимания

Почему игнор?

2022-10-26 15:27 UTC, piton182 commented on src/Main.elm
> +            [ centerX, centerY ]
Этот коммент 7 дней без внимания

Почему игнор?

2022-11-10 11:59 UTC, closed without merging